const express = require('express');
const {ROLES, ADMIN} = require("../../constants/role");
const router = express.Router();
const {isAuth} = require("../../middlewares/auth");
const {createBooking, confirmBooking, getBookingById, getBookings, deleteBooking, countBooking} = require("../../controllers/booking.controller");
router.post('/', isAuth(ROLES), createBooking);
router.post('/confirm/:bookingId', isAuth(ADMIN), confirmBooking);
router.get('/count', isAuth(ROLES), countBooking);
router.get('/:id', isAuth(ADMIN), getBookingById);
router.get('/', isAuth(ADMIN), getBookings);
router.delete('/:id', isAuth(ADMIN), deleteBooking);
module.exports = router;