const express = require('express');
const {getServices, createService, updateServiceById, getServiceById, deleteServiceById} = require("../../controllers/service.controller");
const {isAuth} = require("../../middlewares/auth");
const router = express.Router();
router.get('/', isAuth, getServices);
router.post('/', isAuth, createService);
router.put('/:id', isAuth, updateServiceById);
router.get('/:id', isAuth, getServiceById);
router.delete('/:id', isAuth, deleteServiceById);
module.exports = router;
