import { Inter } from 'next/font/google'
import React, {ReactNode, useEffect} from "react";
import LoadingComponent from "@/components/loading";
import HeaderComponent from "@/components/header";
import FooterComponent from "@/components/footer";
import {usePathname} from "next/navigation";
;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const MainLayout = ({children}: { children: ReactNode }) => {
    const pathname = usePathname();
    return (
        <div data-rsssl="1" className="home page-template-default page page-id-64">
            {/*{pathname && pathname.toString() == process.env.NEXT_PUBLIC_HOME_ROUTER ?*/}
            {/*    <></>*/}
            {/*    :*/}
            {/*    <LoadingComponent/>*/}
            {/*}*/}
            <HeaderComponent/>
                {children}
            <FooterComponent/>
        </div>
    )
}


export default MainLayout
