name: CI/CD Pipeline

on:
  push:
    branches:
      - dev_fe_customer
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y rsync

      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Deploy to server
        env:
          SSHKEY: ${{ secrets.SSHKEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          mkdir -p /home/runner/.ssh
          echo "$SSHKEY" | tr -d '\r' > /home/runner/.ssh/private_key.pem
          chmod 600 /home/runner/.ssh/private_key.pem
          ssh-keyscan -p $PORT -H $HOST >> /home/runner/.ssh/known_hosts

          rsync -avz --delete -e "ssh -i /home/runner/.ssh/private_key.pem -p $PORT -o StrictHostKeyChecking=no" --exclude '.git' --exclude 'node_modules' . $USERNAME@$HOST:/Nails-Or-Never-fe-cus

          ssh -i /home/runner/.ssh/private_key.pem -p $PORT -o StrictHostKeyChecking=no $USERNAME@$HOST "\
            cd /Nails-Or-Never-fe-cus && \
            docker compose stop && \
            docker build -t devfecus . && \
            docker compose up -d --build \
          "
          rm -f /home/runner/.ssh/private_key.pem
